name: Publish Resume to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: read
  id-token: write
  pages: write
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # You can specify your Node.js version here

    # - name: Install markdown-styles
    #   run: npm install -g markdown-styles

    # - name: Generate HTML from Markdown
    #   run: generate-md --layout github --input ./README.md --output ./dist

    # - name: Copy static assets
    #   run: cp -r *.webp dist

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./dist

    - name: Build and Generate Static Files
      run: |
        npm install -g markdown-styles
        generate-md --layout github --input ./README.md --output ./dist
        cp -r *.webp dist

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./dist

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      if: github.ref == 'refs/heads/main'
